# Generated by Django 4.0.4 on 2022-08-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_topping_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'toppings'},
        ),
    ]
