movies = []
print('List of movies:')
print(movies)
movies.append('Terminator')
print(len(movies))
movies.insert(0, "Terminator 2")
print(movies)
movies.append('One')
movies.append('Two')
print(movies)
movies.remove('Two')
print(movies)
del movies[1]
print(movies)
movies.insert(1, 'Avengers')
movies.insert(0, 'Avengers 2')
print(movies)
print(sorted(movies, reverse=True))
movies.reverse()
movies.reverse()
movies.sort()
movies.sort(reverse=True)
print(movies)
print(len(movies))
print(movies[0])
print(movies[1])
print(movies[2])
print(movies[3])
